name: HubTest
on:
  pull_request:
    branches: [ master ]
    
jobs:
  run-hub-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/crowdsecurity/crowdsec
      options: "--entrypoint bash"
      env:
        DISABLE_LOCAL_API: "true"
    env:
      RESULTS_PATH: .
    steps:
    - name: "Set up Go 1.20"
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.4
    - name: checkout repo
      uses: actions/checkout@v3
    - name: checkout hub
      uses: actions/checkout@v3
      with:
        repository: 'crowdsecurity/hub'
        path: hub
    - run: go version
    - name: run tests on last crowdsec tag
      run: |
        apt-get install -y make
        make && cp cmd/crowdsec/crowdsec /usr/local/bin && cp cmd/crowdsec-cli/cscli /usr/local/bin
        cd hub
        cscli hubtest run bitwarden-bg --debug
